os: linux
language: php

# php:
#   - 5.6
#   - 7.2
#   - 7.3
#   - 7.4
  
services:
  - docker

before_install:
- docker build --no-cache -t tamilan/webapp1 .
# - docker run ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} /go/src/github.com/kainlite/whatismyip-go/whatismyip-go.test
- docker run -d -p 127.0.0.1:80:80 tamilan/webapp1

script:
  - curl 127.0.0.1:80
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tamilan/webapp1

notifications: true

# deploy:
#   provider: script
#   script: bash docker_push
#   on:
#     branch: master

